#!/usr/bin/env bash
# Installs nginx server

# Update package index
apt-get update

# Install nginx
apt-get -y install nginx

# (Optional) Allow HTTP traffic via UFW, if UFW is installed
if command -v ufw &> /dev/null; then
    ufw allow 'Nginx HTTP'
fi

# Add simple HTML file
echo "Hello World!" > /var/www/html/index.html

# Start nginx
systemctl start nginx

