#!/usr/bin/env bash
# Configure your nginx server to redirect to another page

apt-get update
apt-get install -y nginx

mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root /etc/nginx/html;
	index index.html index.htm;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=DlJ7t3bKIOo;
	}
}" > /etc/nginx/sites-available/default

sudo service nginx restart
