#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that your servers are configured with the right hostnames

sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend lb-frontend
	bind *:80
	mode http
	default_backend lb-backend

backend lb-backend
	balance roundrobin
	server 279554-web-01 54.87.160.173:80 check
	server 279554-web-02 54.162.87.193:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
