#!/usr/bin/env bash
# Script to terminate a process

PID=$(pgrep 4-to_infinity_and_beyond)

if [ -z "$PID" ]; then
	echo "Process 4-to_infinity_and_beyond is not running."
else
	killall "$PID"
	wait "$PID" 2>/dev/null
	if ps -p "$PID" > /dev/null; then
		kill -9 "$PID"
	else
		echo "Terminated"
	fi
fi
