#!/usr/bin/env bash
# Displays 1 to 100
#	FizzBuzz if divisible by 3 and 5
#	Fizz if divisible by 3
#	Buzz if divisible by 5

i=1

while [ $i -le 100 ]; do
	if [ $((i % 15)) -eq 0 ]; then
		echo 'FizzBuzz'
	elif [ $((i % 3)) -eq 0 ]; then
		echo 'Fizz'
	elif [ $((i % 5)) -eq 0 ]; then
		echo 'Buzz'
	else
		echo "$i"
	fi
	i=$((i+1))
done
