#!/usr/bin/env bash
# Tell the story of passwd

while IFS=: read -r user_name password user_id group_id user_id_info home_dir command; do
	echo -n "The user $user_name is part of the $group_id gang, "
	echo -n "lives in $home_dir and rides $command. "
	echo -n "$user_id's is protected by the passcode $password, "
	echo -n "more info about the user here: $user_id_info."
	echo
done < /etc/passwd
