#!/usr/bin/env bash
# Dispalys diff test for 4 and 8 iteration

NAME="Best School"
i="1"

while [ $i -lt 11 ]; do
	if [ $i -eq 4 ]
	then
		echo 'bad luck'
	elif [ $i -eq 8 ]
	then
		echo 'good luck'
	else
		echo "$NAME"
	fi
	i=$((i+1))
done
