#!/usr/bin/env bash
# Script that displays superstitious numbers using case control flow

BAD="bad luck from China"
BAD1="bad luck from Japan"
BAD2="bad luck from Italy"
i="1"

while [ $i -le 20 ]; do
	case $i in
		4)
			echo "$i"
			echo "$BAD"
			;;
		9)
			echo "$i"
			echo "$BAD1"
			;;
		17)
			echo "$i"
			echo "$BAD2"
			;;
		*)
			echo $i
			;;
	esac
	i=$((i+1))
done
