#!/usr/bin/env bash
# Script to give information about `school` file

file_path=$(find . -name "school")

if [ -e "$file_path" ]
then
	echo 'school file exists'
	if [ -s "$file_path" ]
	then
		echo 'school file is not empty'
	fi
	if [ -f "$file_path" ]
	then
		echo 'school is a regular file'
	fi
else
	echo 'school file does not exist'
fi
